package CookBloks::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';
use Catalyst qw{ ConfigLoader };

# removing config in favour of config file
=pod
__PACKAGE__->config(
    schema_class => 'CookBloks::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=recipes',
        user => 'catappuser',
        password => 'catalyst',
        AutoCommit => q{1},
    }
);
=cut

=head1 NAME

CookBloks::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<CookBloks>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<CookBloks::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Paul Newell

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
