package CookBloks::Model::RecipeDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'CookBloks::Schema::RecipeDB',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=recipedb;host=pgn.no-ip.org',
        user => 'catappuser',
        password => 'catalyst',
    }
);

=head1 NAME

CookBloks::Model::RecipeDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<CookBloks>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<CookBloks::Schema::RecipeDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
