package ActiveCookbook::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MyApp::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=ActiveRecip',
        user => 'catappuser',
        password => 'catalyst',
        AutoCommit => q{1},
    }
);

=head1 NAME

ActiveCookbook::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<ActiveCookbook>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MyApp::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Paul Newell

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
